### ISSUE TITLE
CHER and FetchSlide

### ISSUE THREAD

**Issue by nikisim** [FSLight1996/SHER#1]
Hi!

Have you tried launching the CHER algorithm on the FetchSlide-v1 environment? Did you get a good result? And if so, could you share hyperparameters for CHER on FetchSlide?

Thanks

**Comment by FSLight1996** [comment]
Dear nikisim，
&nbsp; &nbsp; Although I think the field is too involute and academically watered down, leading to a change of direction during the PhD period，I'm still curious about how some of the environments inside like HandManipulatePen should achieve a 90%+ task completion rate.&nbsp;
&nbsp; &nbsp;&nbsp;I think the FetchSlide environment is still relatively easy, and you can refer to YangRui2015/Modular_HER for the parameters because the author had an internship at Tencent AI Lab(CHER's first author institution).
&nbsp; &nbsp; However, CHER is not a good baseline as TOPDM(https://dexterous-manipulation.github.io/) from "Solving Challenging Dexterous Manipulation Tasks With Trajectory Optimisation and Reinforcement Learning", which I think is the SOTA open source algorithm for Hand tasks.&nbsp;
&nbsp; &nbsp;&nbsp;Hope it can help you.
Best wishes,
FSLight




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月27日(星期三) 晚上8:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [FSLight1996/SHER] CHER and FetchSlide (Issue #1)





 
Hi!
 
Have you tried launching the CHER algorithm on the FetchSlide-v1 environment? Did you get a good result? And if so, could you share hyperparameters for CHER on FetchSlide?
 
Thanks

**Comment by nikisim** [comment]
Thank you for help and fast response!
